version: '3'
services:
  web:
    image: nginx
    ports:
      - "80:8080"
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
