---
apiVersion: v1
kind: Secret
metadata:
  name: webkubectl-sec
stringData:
  creds: user01:password02
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webkubectl
  name: webkubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webkubectl
  template:
    metadata:
      labels:
        app: webkubectl
    spec:
      containers:
      - image: kubeoperator/webkubectl
        name: webkubectl
        ports:
        - containerPort: 8080
        env:
        - name: GOTTY_CREDENTIAL
          valueFrom:
            secretKeyRef:
              name: webkubectl-sec
              key: creds
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webkubectl
  name: webkubectl
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webkubectl
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webkubectl
  name: webkubectl
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webkubectl
  type: NodePort
